# Generated by Django 5.2.4 on 2026-05-22 09:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['state__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('flag', models.CharField(choices=[('GREEN', 'Green Flag'), ('ORANGE', 'Orange Flag'), ('RED', 'Red Flag')], default='GREEN', max_length=20)),
                ('yearly_target_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('achieved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('approval_status', models.CharField(choices=[('PENDING_ASM', 'Pending ASM Approval'), ('FORWARDED_RM', 'Forwarded to Regional Manager'), ('FORWARDED_STATE_HEAD', 'Forwarded to State Head'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_ASM', max_length=40)),
                ('asm_approved_at', models.DateTimeField(blank=True, null=True)),
                ('regional_manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('state_head_approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asm_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_asm_approvals', to=settings.AUTH_USER_MODEL)),
                ('concerned_asm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers_under_asm', to=settings.AUTH_USER_MODEL)),
                ('created_by_sales_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers_created_by_sales_officer', to=settings.AUTH_USER_MODEL)),
                ('forwarded_regional_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers_forwarded_to_rm', to=settings.AUTH_USER_MODEL)),
                ('forwarded_state_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers_forwarded_to_state_head', to=settings.AUTH_USER_MODEL)),
                ('regional_manager_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_rm_approvals', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_rejections', to=settings.AUTH_USER_MODEL)),
                ('state_head_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_state_head_approvals', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.district')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state')),
            ],
        ),
        migrations.CreateModel(
            name='DealerApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('ASM_APPROVED', 'ASM Approved'), ('FORWARDED_RM', 'Forwarded to Regional Manager'), ('RM_APPROVED', 'Regional Manager Approved'), ('FORWARDED_STATE_HEAD', 'Forwarded to State Head'), ('STATE_HEAD_APPROVED', 'State Head Approved'), ('REJECTED', 'Rejected')], max_length=40)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='core.dealer')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerMeetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('meeting_date', models.DateField()),
                ('expected_farmer_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING_SALES_OFFICER', 'Pending Sales Officer'), ('PENDING_ASM', 'Pending ASM'), ('PENDING_REGIONAL_MANAGER', 'Pending Regional Manager'), ('PENDING_STATE_HEAD', 'Pending State Head'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_SALES_OFFICER', max_length=40)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asm_farmer_meets', to=settings.AUTH_USER_MODEL)),
                ('created_by_mdo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_farmer_meets', to=settings.AUTH_USER_MODEL)),
                ('regional_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_farmer_meets', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_farmer_meets', to=settings.AUTH_USER_MODEL)),
                ('sales_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_officer_farmer_meets', to=settings.AUTH_USER_MODEL)),
                ('state_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_head_farmer_meets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerMeetApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farmer_meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='core.farmermeetrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.state'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('ACCOUNTANT', 'Accountant'), ('HR', 'HR'), ('STATE_HEAD', 'State Head'), ('REGIONAL_MANAGER', 'Regional Manager'), ('ASM', 'Area Sales Manager'), ('SALES_OFFICER_SENIOR', 'Senior Sales Officer'), ('SALES_OFFICER_JUNIOR', 'Junior Sales Officer'), ('WAREHOUSE_MANAGER', 'Warehouse Manager'), ('PRODUCTION_INCHARGE', 'Production Incharge'), ('DEVELOPMENT_OFFICER', 'Market Development Officer'), ('DEALER', 'Dealer')], max_length=40)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.district')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeYearlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2026)),
                ('target_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('achieved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_yearly_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('employee', 'year')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('state', 'name')},
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='core.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='core.state')),
                ('warehouse_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['state__name', 'district__name', 'name'],
                'unique_together': {('district', 'name')},
            },
        ),
    ]
