# Generated by Django 5.2.4 on 2026-05-22 09:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='salary_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly salary amount', max_digits=12),
        ),
    ]
