# Generated by Django 5.2.4 on 2026-05-22 10:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_salary_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='address',
            new_name='firm_address',
        ),
        migrations.AddField(
            model_name='dealer',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='dealer_image',
            field=models.ImageField(blank=True, null=True, upload_to='dealer_images/'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('15000.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='dealer',
            name='deposit_mode',
            field=models.CharField(choices=[('CHEQUE', 'Cheque')], default='CHEQUE', max_length=20),
        ),
        migrations.AddField(
            model_name='dealer',
            name='firm_type',
            field=models.CharField(choices=[('OWNED', 'Owned'), ('RENTED', 'Rented'), ('LEASED', 'Leased')], default='OWNED', max_length=20),
        ),
        migrations.AddField(
            model_name='dealer',
            name='gst_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='GST Number'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='license_number',
            field=models.CharField(blank=True, help_text='Optional', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='owner_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Assigned reporting manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
