# Generated by Django 5.2.4 on 2026-05-22 12:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_address_dealer_firm_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DealerCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('hsn_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.productcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryPaymentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('ADVANCE', 'Advance Payment'), ('INSTANT', 'Instant Payment'), ('DAY_RANGE', 'Day Wise Payment')], max_length=20)),
                ('title', models.CharField(help_text='Example: 1 to 20 Days Payment Discount', max_length=120)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('from_day', models.PositiveIntegerField(blank=True, null=True)),
                ('to_day', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_rules', to='core.productcategory')),
            ],
            options={
                'ordering': ['category', 'rule_type', 'from_day'],
            },
        ),
        migrations.CreateModel(
            name='ProductPackSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_size', models.DecimalField(decimal_places=2, help_text='Example: 1, 5, 25, 100', max_digits=10)),
                ('unit', models.CharField(choices=[('GRAM', 'Gram'), ('KG', 'Kg'), ('ML', 'ML'), ('LITRE', 'Litre'), ('PIECE', 'Piece')], default='KG', max_length=20)),
                ('packing_type', models.CharField(choices=[('BAG', 'Bag'), ('BOX', 'Box'), ('BOTTLE', 'Bottle'), ('PACKET', 'Packet'), ('CARTON', 'Carton'), ('PIECE', 'Piece')], default='BAG', max_length=20)),
                ('units_per_box', models.PositiveIntegerField(default=1, help_text='Example: 1KG bag × 25 pieces in one box')),
                ('mrp_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sale_price_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('purchase_price_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Internal purchase price, not shown to dealer', max_digits=12)),
                ('box_sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total sale price for full box/bag/carton', max_digits=14)),
                ('stock_boxes', models.PositiveIntegerField(default=0, help_text='Available boxes/cartons/bags for this pack')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_sizes', to='core.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_pack_sizes', to='core.warehouse')),
            ],
            options={
                'ordering': ['product', 'pack_size'],
            },
        ),
        migrations.CreateModel(
            name='ProductScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=160)),
                ('scheme_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('FREE_QTY', 'Free Quantity')], default='DISCOUNT', max_length=20)),
                ('min_boxes', models.PositiveIntegerField(default=1)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('free_boxes', models.PositiveIntegerField(default=0, help_text='Example: Buy 10 boxes, get 1 box free')),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pack_size', models.ForeignKey(blank=True, help_text='Leave empty if scheme applies to all pack sizes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemes', to='core.productpacksize')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='core.product')),
            ],
            options={
                'ordering': ['product', 'min_boxes'],
            },
        ),
        migrations.CreateModel(
            name='DealerCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_boxes', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.dealercart')),
                ('product_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='core.productpacksize')),
            ],
            options={
                'unique_together': {('cart', 'product_pack')},
            },
        ),
    ]
