# Generated by Django 5.2.4 on 2026-05-22 14:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productcategory_dealercart_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=10, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DealerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_flag', models.CharField(choices=[('GREEN', 'Green'), ('ORANGE', 'Orange'), ('RED', 'Red')], max_length=20)),
                ('status', models.CharField(choices=[('PLACED', 'Order Placed'), ('REJECTED', 'Rejected'), ('SALES_APPROVAL', 'Sales Officer Approval Pending'), ('ASM_APPROVAL', 'ASM Approval Pending'), ('RSM_APPROVAL', 'Regional Manager Approval Pending'), ('ACCOUNTANT_ORDER_APPROVAL', 'Accountant Order Approval Pending'), ('WAREHOUSE_REVIEW', 'Warehouse Review Pending'), ('ACCOUNTANT_INVOICE_REVIEW', 'Accountant Invoice Review Pending'), ('INVOICE_RELEASED', 'Invoice Released'), ('DISPATCH_PENDING', 'Dispatch Pending'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered')], default='PLACED', max_length=40)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_approved_at', models.DateTimeField(blank=True, null=True)),
                ('asm_approved_at', models.DateTimeField(blank=True, null=True)),
                ('rsm_approved_at', models.DateTimeField(blank=True, null=True)),
                ('accountant_order_approved_at', models.DateTimeField(blank=True, null=True)),
                ('warehouse_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_released_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('concerned_asm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asm_orders', to=settings.AUTH_USER_MODEL)),
                ('concerned_rsm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsm_orders', to=settings.AUTH_USER_MODEL)),
                ('concerned_sales_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.dealer')),
                ('dealer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dealer_orders', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_dealer_orders', to=settings.AUTH_USER_MODEL)),
                ('warehouse_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='DealerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=10)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('place_of_supply', models.CharField(blank=True, max_length=120, null=True)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.dealerorder')),
            ],
        ),
        migrations.CreateModel(
            name='DealerDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('OWN', 'Own Transport'), ('OTHER', 'Other Transport')], max_length=20)),
                ('vehicle_name', models.CharField(blank=True, max_length=120, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=80, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=120, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('other_transport_tracking_id', models.CharField(blank=True, max_length=120, null=True)),
                ('dispatch_date', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='core.dealerorder')),
            ],
        ),
        migrations.CreateModel(
            name='DealerOrderApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FORWARDED', 'Forwarded'), ('CREATED', 'Created'), ('INVOICE_RELEASED', 'Invoice Released'), ('DISPATCHED', 'Dispatched')], max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='core.dealerorder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180)),
                ('pack_label', models.CharField(max_length=80)),
                ('quantity_boxes', models.PositiveIntegerField(default=1)),
                ('units_per_box', models.PositiveIntegerField(default=1)),
                ('total_units', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_name', models.CharField(default='Pcs', max_length=30)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('box_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=80, null=True)),
                ('mfg_date', models.CharField(blank=True, max_length=20, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=20, null=True)),
                ('warehouse_checked', models.BooleanField(default=False)),
                ('accountant_checked', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.dealerorder')),
                ('product_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='core.productpacksize')),
            ],
        ),
    ]
