# Generated by Django 5.2.4 on 2026-05-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_invoicenumbersequence_dealerorder_dealerinvoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerorderapprovallog',
            name='action',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FORWARDED', 'Forwarded'), ('CREATED', 'Created'), ('INVOICE_RELEASED', 'Invoice Released'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered')], max_length=30),
        ),
    ]
