# Generated by Django 5.2.4 on 2026-05-22 15:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_dealerorderapprovallog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='dealerinvoice',
            name='final_payable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='dealerinvoice',
            name='is_converted_to_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealerinvoice',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerinvoice',
            name='sales_converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerinvoice',
            name='sales_converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_sales_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DealerInvoiceEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='core.dealerinvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealerInvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('FULL', 'Full Payment'), ('PARTIAL', 'Partial Payment')], max_length=20)),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('gross_invoice_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_type', models.CharField(choices=[('NONE', 'No Discount'), ('CATEGORY_RULE', 'Category Payment Rule'), ('MANUAL', 'Manual Discount')], default='NONE', max_length=30)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_received_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance_after_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('category_rule_note', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_reference_number', models.CharField(blank=True, max_length=120, null=True)),
                ('bank_transaction_number', models.CharField(blank=True, max_length=120, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=120, null=True)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='invoice_payments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoice_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.dealerinvoice')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
