# Generated by Django 5.2.4 on 2026-05-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dealerinvoice_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerinvoicepayment',
            name='selected_category_rule_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerinvoicepayment',
            name='selected_category_rule_key',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dealerinvoicepayment',
            name='selected_category_rule_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dealerinvoicepayment',
            name='selected_category_rule_order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
