# Generated by Django 5.2.4 on 2026-05-22 17:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dealerinvoicepayment_selected_category_rule_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='Example: Axis Bank Main Account', max_length=150)),
                ('bank_name', models.CharField(max_length=150)),
                ('branch_name', models.CharField(blank=True, max_length=150, null=True)),
                ('account_number', models.CharField(max_length=80)),
                ('ifsc_code', models.CharField(max_length=30)),
                ('account_holder_name', models.CharField(max_length=180)),
                ('bank_address', models.TextField(blank=True, help_text='Bank branch address', null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPaymentIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('DEALER', 'Dealer Payment'), ('CASH_TO_BANK', 'Cash to Bank'), ('OWNER_DEPOSIT', 'Owner Deposit'), ('OTHER', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash')], max_length=20)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference_number', models.CharField(blank=True, help_text='UPI reference / bank transaction number', max_length=150, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='company_payment_in/')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_ins', to='core.companyaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_payment_ins', to='core.dealer')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPaymentOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('TRANSPORT', 'Transport'), ('PURCHASE', 'Purchase'), ('RENT', 'Rent'), ('BANK_CHARGES', 'Bank Charges'), ('SALARY', 'Salary'), ('OFFICE_EXPENSES', 'Office Expenses'), ('OTHER', 'Other')], max_length=40)),
                ('payee_name', models.CharField(blank=True, help_text='Person/vendor/company name', max_length=180, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash')], max_length=20)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference_number', models.CharField(blank=True, help_text='UPI reference / bank transaction number', max_length=150, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='company_payment_out/')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_outs', to='core.companyaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
