# Generated by Django 5.2.4 on 2026-05-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_companyaccount_companypaymentin_companypaymentout'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='dealer_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
