# Generated by Django 5.2.4 on 2026-05-22 18:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dealer_dealer_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNoteNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=10, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='dealerinvoice',
            name='net_payable_after_return',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final payable amount after reducing sales return credit notes', max_digits=14),
        ),
        migrations.AddField(
            model_name='dealerinvoice',
            name='return_credit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total sales return / credit note amount adjusted against this invoice', max_digits=14),
        ),
        migrations.CreateModel(
            name='SalesReturnCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('return_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.TextField()),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], default='RELEASED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_notes', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_credit_notes', to='core.dealer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_credit_notes', to='core.dealerinvoice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_credit_notes', to='core.dealerorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_credit_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-return_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnCreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(max_length=180)),
                ('pack_label_snapshot', models.CharField(max_length=80)),
                ('sold_quantity_boxes', models.PositiveIntegerField(default=0)),
                ('return_quantity_boxes', models.PositiveIntegerField(default=1)),
                ('units_per_box', models.PositiveIntegerField(default=1)),
                ('total_return_units', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_name', models.CharField(default='Pcs', max_length=30)),
                ('price_per_box', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=80, null=True)),
                ('mfg_date', models.CharField(blank=True, max_length=20, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=20, null=True)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.salesreturncreditnote')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_items', to='core.dealerorderitem')),
                ('product_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_items', to='core.productpacksize')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
