# Generated by Django 5.2.4 on 2026-05-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_creditnotenumbersequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturncreditnote',
            name='show_to_dealer',
            field=models.BooleanField(default=False, help_text='Only if enabled, dealer can see this credit note'),
        ),
    ]
