# Generated by Django 5.2.4 on 2026-05-23 12:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_salesreturncreditnote_show_to_dealer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bike_ta_per_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='car_ta_per_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_da_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='duty_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='duty_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_code',
            field=models.CharField(blank=True, help_text='Employee ID', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_leaves_per_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paid_leaves_per_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sick_leaves_per_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unpaid_leaves_per_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(default=django.utils.timezone.localdate)),
                ('clock_in_at', models.DateTimeField(blank=True, null=True)),
                ('clock_in_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('clock_in_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('clock_out_at', models.DateTimeField(blank=True, null=True)),
                ('clock_out_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('clock_out_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('BIKE', 'Bike'), ('CAR', 'Car'), ('PUBLIC', 'Public Vehicle'), ('COMPANY', 'Company Vehicle')], max_length=20, null=True)),
                ('dealers_connected_count', models.PositiveIntegerField(default=0)),
                ('dealer_visit_image_1', models.ImageField(blank=True, null=True, upload_to='attendance/dealer_visits/')),
                ('dealer_visit_image_2', models.ImageField(blank=True, null=True, upload_to='attendance/dealer_visits/')),
                ('public_vehicle_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('public_vehicle_bill', models.FileField(blank=True, null=True, upload_to='attendance/public_vehicle_bills/')),
                ('system_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('manager_approved_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ta_rate_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ta_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('da_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_claim_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('CLOCKED_IN', 'Clocked In'), ('PENDING_MANAGER', 'Pending Manager Approval'), ('MANAGER_APPROVED', 'Manager Approved'), ('HR_APPROVED', 'HR Approved'), ('RELEASED', 'Released'), ('REJECTED', 'Rejected')], default='CLOCKED_IN', max_length=30)),
                ('manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('manager_remarks', models.TextField(blank=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hr_remarks', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('hr_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approved_attendance', to=settings.AUTH_USER_MODEL)),
                ('manager_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approved_attendance', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_attendance_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attendance_date', '-clock_in_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeGPSTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_points', to='core.employeeattendance')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('PAID', 'Paid Leave'), ('SICK', 'Sick Leave'), ('OTHER', 'Other Leave'), ('UNPAID', 'Unpaid Leave')], max_length=20)),
                ('day_type', models.CharField(choices=[('FULL_DAY', 'Full Day'), ('HALF_DAY', 'Half Day')], default='FULL_DAY', max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Manager Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('manager_remarks', models.TextField(blank=True)),
                ('salary_deduction_required', models.BooleanField(default=False)),
                ('deduction_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
