# Generated by Django 5.2.4 on 2026-05-23 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_employeepayslip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='earned_extra_other_leaves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_wednesday',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EmployeeExtraWorkDayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING_MANAGER', 'Pending Manager Approval'), ('MANAGER_APPROVED_PENDING_HR', 'Manager Approved - Pending HR'), ('HR_APPROVED', 'HR Approved / Extra Leave Added'), ('REJECTED', 'Rejected')], default='PENDING_MANAGER', max_length=40)),
                ('manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('manager_remarks', models.TextField(blank=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hr_remarks', models.TextField(blank=True)),
                ('extra_leave_added', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_work_day_requests', to=settings.AUTH_USER_MODEL)),
                ('hr_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approved_extra_work_days', to=settings.AUTH_USER_MODEL)),
                ('manager_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approved_extra_work_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
                'unique_together': {('employee', 'work_date')},
            },
        ),
    ]
