# Generated by Django 5.2.4 on 2026-05-25 07:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userprofile_earned_extra_other_leaves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manager_target_extra_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra target percentage over direct reporting employees target. Example: 50 means team target + 50%.', max_digits=6),
        ),
    ]
