# Generated by Django 5.2.4 on 2026-05-25 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userprofile_manager_target_extra_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStickerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_mm', models.DecimalField(decimal_places=2, default=90, max_digits=6)),
                ('height_mm', models.DecimalField(decimal_places=2, default=70, max_digits=6)),
                ('copies', models.PositiveIntegerField(default=12)),
                ('company_name', models.CharField(default='ARVIS FERTILIZERS & CHEMICALS PVT. LTD.', max_length=255)),
                ('company_subtitle', models.CharField(default='PRODUCT LABEL / STICKER', max_length=255)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('hsn_code', models.CharField(blank=True, max_length=50)),
                ('qty_per_case', models.CharField(blank=True, max_length=100)),
                ('batch_no', models.CharField(blank=True, max_length=100)),
                ('mfg_date', models.CharField(blank=True, max_length=100)),
                ('exp_date', models.CharField(blank=True, max_length=100)),
                ('unit_mrp', models.CharField(blank=True, max_length=100)),
                ('case_mrp', models.CharField(blank=True, max_length=100)),
                ('barcode_value', models.CharField(blank=True, max_length=100)),
                ('usp_text', models.CharField(blank=True, max_length=150)),
                ('show_qr', models.BooleanField(default=True)),
                ('footer_text', models.CharField(default='Scan QR for product details.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productpacksize')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sticker_setting', to='core.product')),
            ],
        ),
    ]
