# Generated by Django 5.2.4 on 2026-05-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_productstickersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstickersetting',
            name='company_address',
            field=models.CharField(default='Company Address, Telangana, India', max_length=300),
        ),
        migrations.AddField(
            model_name='productstickersetting',
            name='company_email',
            field=models.EmailField(blank=True, default='info@arvisfertilizers.com', max_length=150),
        ),
        migrations.AddField(
            model_name='productstickersetting',
            name='company_website',
            field=models.CharField(blank=True, default='www.arvisfertilizers.com', max_length=150),
        ),
        migrations.AddField(
            model_name='productstickersetting',
            name='customer_care',
            field=models.CharField(blank=True, default='8500352005', max_length=50),
        ),
        migrations.AddField(
            model_name='productstickersetting',
            name='manufactured_by',
            field=models.CharField(blank=True, default='ARVIS FERTILIZERS & CHEMICALS PVT. LTD.', max_length=255),
        ),
        migrations.AddField(
            model_name='productstickersetting',
            name='marketed_by',
            field=models.CharField(blank=True, default='ARVIS FERTILIZERS & CHEMICALS PVT. LTD.', max_length=255),
        ),
        migrations.AddField(
            model_name='productstickersetting',
            name='show_barcode',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productstickersetting',
            name='copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productstickersetting',
            name='height_mm',
            field=models.DecimalField(decimal_places=2, default=75, max_digits=6),
        ),
        migrations.AlterField(
            model_name='productstickersetting',
            name='width_mm',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
    ]
