# Generated by Django 5.2.4 on 2026-05-25 14:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_productstickersetting_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstickersetting',
            name='body_font_mm',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.25'), max_digits=5),
        ),
    ]
