# Generated by Django 5.2.4 on 2026-05-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ACCOUNTANT', 'Accountant'), ('HR', 'HR'), ('STATE_HEAD', 'State Head'), ('REGIONAL_MANAGER', 'Regional Manager'), ('ASM', 'Area Sales Manager'), ('SALES_OFFICER_SENIOR', 'Senior Sales Officer'), ('SALES_OFFICER_JUNIOR', 'Junior Sales Officer'), ('WAREHOUSE_MANAGER', 'Warehouse Manager'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('DEVELOPMENT_OFFICER', 'Market Development Officer'), ('ASSET_MANAGER', 'Asset Manager'), ('DEALER', 'Dealer')], max_length=40),
        ),
    ]
