# Generated by Django 5.2.4 on 2026-05-26 07:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_assetcategory_assetitem_assetassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerPointSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_points', models.PositiveIntegerField(default=5)),
                ('rupees_per_point', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('minimum_money_redemption_points', models.PositiveIntegerField(default=100)),
                ('minimum_product_redemption_points', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dealer Point Setting',
                'verbose_name_plural': 'Dealer Point Settings',
            },
        ),
        migrations.CreateModel(
            name='DealerPointProductRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('points_required', models.PositiveIntegerField()),
                ('free_quantity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pack_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_redemption_rules', to='core.productpacksize')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_redemption_rules', to='core.product')),
            ],
            options={
                'ordering': ['product__name', 'points_required'],
            },
        ),
        migrations.CreateModel(
            name='DealerPointRedemptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redemption_type', models.CharField(choices=[('MONEY', 'Money'), ('PRODUCT', 'Product / Free Quantity')], max_length=20)),
                ('points_requested', models.PositiveIntegerField()),
                ('money_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('request_quantity', models.PositiveIntegerField(default=1)),
                ('requested_free_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING_SALES_OFFICER', 'Pending Sales Officer'), ('PENDING_ASM', 'Pending ASM'), ('PENDING_ACCOUNTANT', 'Pending Accountant'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_SALES_OFFICER', max_length=40)),
                ('sales_officer_approved_at', models.DateTimeField(blank=True, null=True)),
                ('asm_approved_at', models.DateTimeField(blank=True, null=True)),
                ('accountant_approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant_point_redemptions', to=settings.AUTH_USER_MODEL)),
                ('asm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asm_point_redemptions', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_redemption_requests', to='core.dealer')),
                ('product_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemption_requests', to='core.dealerpointproductrule')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_point_redemptions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_point_redemptions_created', to=settings.AUTH_USER_MODEL)),
                ('sales_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_officer_point_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('place', models.CharField(max_length=255)),
                ('points_awarded', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_farmer_data', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_data', to='core.dealer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealerPointLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('points', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_ledger', to='core.dealer')),
                ('redemption_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_entries', to='core.dealerpointredemptionrequest')),
                ('farmer_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_entries', to='core.farmerdata')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
