# Generated by Django 5.2.4 on 2026-05-29 07:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_dealerpointsetting_dealerpointproductrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayslip',
            name='employee_bank_account_holder_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='employee_bank_account_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='employee_bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='employee_bank_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='employee_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='employee_insurance_policy_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='employee_insurance_provider_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='employee_pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='employee_pf_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='employee_pf_uan_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='insurance_deduction_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='pf_deduction_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Employee date of birth', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='insurance_applicable',
            field=models.BooleanField(default=False, help_text='Is employee related to company insurance?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='insurance_deduction_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly insurance deduction from salary', max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='insurance_provider_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN Number', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pf_applicable',
            field=models.BooleanField(default=False, help_text='Is PF applicable for this employee?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pf_deduction_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Example: 12 means 12% PF deduction from salary', max_digits=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pf_uan_number',
            field=models.CharField(blank=True, help_text='PF UAN Number', max_length=30, null=True),
        ),
    ]
