# Generated by Django 5.2.4 on 2026-06-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_employeepayslip_employee_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='clock_in_odometer_reading',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Odometer reading entered by employee during clock-in', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='clock_out_odometer_reading',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Odometer reading entered by employee during clock-out', max_digits=12, null=True),
        ),
    ]
