# Generated by Django 5.2.4 on 2026-06-03 07:22

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_employeeattendance_clock_in_odometer_reading_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('visit_time', models.TimeField(default=core.models.current_local_time)),
                ('reason', models.CharField(choices=[('REGULAR_VISIT', 'Regular Visit'), ('PAYMENT_FOLLOWUP', 'Payment Follow-up'), ('ORDER_FOLLOWUP', 'Order Follow-up'), ('PRODUCT_PROMOTION', 'Product Promotion'), ('COMPLAINT_VISIT', 'Complaint Visit'), ('STOCK_CHECK', 'Stock Check'), ('SCHEME_EXPLANATION', 'Scheme Explanation'), ('OTHER', 'Other')], default='REGULAR_VISIT', max_length=40)),
                ('note', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('visit_image', models.ImageField(blank=True, null=True, upload_to='dealer_visits/original/')),
                ('stamped_image', models.ImageField(blank=True, null=True, upload_to='dealer_visits/stamped/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_visits', to='core.dealer')),
                ('sales_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date', '-visit_time', '-created_at'],
            },
        ),
    ]
