# Generated by Django 5.2.4 on 2026-06-03 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_dealervisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='credit_score',
            field=models.PositiveSmallIntegerField(default=650, help_text='Dealer credit score between 300 and 900'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='credit_score_change_points',
            field=models.IntegerField(default=0, help_text='Last score change points. Example: 71 or -20'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='credit_score_note',
            field=models.CharField(blank=True, help_text='Reason/note for credit score update', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='credit_score_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='credit_score_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_credit_score_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DealerCreditScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_score', models.PositiveSmallIntegerField(default=650)),
                ('new_score', models.PositiveSmallIntegerField(default=650)),
                ('change_points', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_score_history', to='core.dealer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
