# Generated by Django 5.2.4 on 2026-06-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_dealer_credit_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='location_accuracy_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='visit_radius_meters',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='dealervisit',
            name='distance_from_dealer_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dealervisit',
            name='gps_accuracy_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='dealervisit',
            name='location_verified',
            field=models.BooleanField(default=False),
        ),
    ]
