# Generated by Django 5.2.4 on 2026-06-04 06:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_dealer_latitude_dealer_location_accuracy_meters_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('PACKING_MATERIAL', 'Packing Material'), ('SEMI_FINISHED', 'Semi Finished'), ('FINISHED', 'Finished'), ('OTHER', 'Other')], default='RAW_MATERIAL', max_length=40)),
                ('name', models.CharField(max_length=180)),
                ('sku_code', models.CharField(blank=True, max_length=80, null=True)),
                ('stock_unit', models.CharField(choices=[('GRAM', 'Gram'), ('KG', 'Kg'), ('ML', 'ML'), ('LITRE', 'Litre'), ('PIECE', 'Piece'), ('BAG', 'Bag'), ('BOX', 'Box'), ('BOTTLE', 'Bottle'), ('PACKET', 'Packet'), ('CARTON', 'Carton')], default='KG', max_length=20)),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('average_purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('minimum_stock_alert', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=180)),
                ('party_type', models.CharField(choices=[('SUPPLIER', 'Supplier'), ('MANUFACTURER', 'Manufacturer'), ('DISTRIBUTOR', 'Distributor'), ('OTHER', 'Other')], default='SUPPLIER', max_length=30)),
                ('contact_person', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['party_name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryStockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('PURCHASE', 'Purchase'), ('PURCHASE_RETURN', 'Purchase Return'), ('PRODUCTION_USE', 'Production Use'), ('REPACK_USE', 'Repack Use'), ('ADJUSTMENT', 'Adjustment')], max_length=40)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit', models.CharField(choices=[('GRAM', 'Gram'), ('KG', 'Kg'), ('ML', 'ML'), ('LITRE', 'Litre'), ('PIECE', 'Piece'), ('BAG', 'Bag'), ('BOX', 'Box'), ('BOTTLE', 'Bottle'), ('PACKET', 'Packet'), ('CARTON', 'Carton')], max_length=20)),
                ('balance_after', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('reference_model', models.CharField(blank=True, max_length=80, null=True)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger', to='core.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('output_boxes', models.PositiveIntegerField(default=1, help_text='How many final product boxes this recipe creates')),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('output_product_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_recipes', to='core.productpacksize')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('production_date', models.DateField(default=django.utils.timezone.localdate)),
                ('output_boxes', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('stock_applied', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_batches', to=settings.AUTH_USER_MODEL)),
                ('output_product_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_outputs', to='core.productpacksize')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='core.productionrecipe')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit', models.CharField(choices=[('GRAM', 'Gram'), ('KG', 'Kg'), ('ML', 'ML'), ('LITRE', 'Litre'), ('PIECE', 'Piece'), ('BAG', 'Bag'), ('BOX', 'Box'), ('BOTTLE', 'Bottle'), ('PACKET', 'Packet'), ('CARTON', 'Carton')], max_length=20)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='core.inventoryitem')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='core.productionrecipe')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=80)),
                ('bill_date', models.DateField(default=django.utils.timezone.localdate)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('return_credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=20)),
                ('stock_added', models.BooleanField(default=False)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='purchase_bills/')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit', models.CharField(choices=[('GRAM', 'Gram'), ('KG', 'Kg'), ('ML', 'ML'), ('LITRE', 'Litre'), ('PIECE', 'Piece'), ('BAG', 'Bag'), ('BOX', 'Box'), ('BOTTLE', 'Bottle'), ('PACKET', 'Packet'), ('CARTON', 'Carton')], max_length=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchasebill')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bill_items', to='core.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ORDERED', 'Ordered'), ('BILLED', 'Billed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.purchaseparty')),
                ('purchase_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='core.purchasetype')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_bills', to='core.purchaseorder'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit', models.CharField(choices=[('GRAM', 'Gram'), ('KG', 'Kg'), ('ML', 'ML'), ('LITRE', 'Litre'), ('PIECE', 'Piece'), ('BAG', 'Bag'), ('BOX', 'Box'), ('BOTTLE', 'Bottle'), ('PACKET', 'Packet'), ('CARTON', 'Carton')], max_length=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='core.inventoryitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchaseorder')),
            ],
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bills', to='core.purchaseparty'),
        ),
        migrations.CreateModel(
            name='PurchasePaymentOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=120, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=80, null=True)),
                ('payment_screenshot', models.FileField(blank=True, null=True, upload_to='purchase_payments/')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.purchasebill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_payments', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_payments', to='core.purchaseparty')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_note_number', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('return_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.TextField()),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('stock_reduced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns', to='core.purchasebill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='core.purchaseparty')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit', models.CharField(choices=[('GRAM', 'Gram'), ('KG', 'Kg'), ('ML', 'ML'), ('LITRE', 'Litre'), ('PIECE', 'Piece'), ('BAG', 'Bag'), ('BOX', 'Box'), ('BOTTLE', 'Bottle'), ('PACKET', 'Packet'), ('CARTON', 'Carton')], max_length=20)),
                ('return_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_items', to='core.inventoryitem')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchasereturnorder')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='core.purchasetype'),
        ),
        migrations.CreateModel(
            name='RepackingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('repack_date', models.DateField(default=django.utils.timezone.localdate)),
                ('source_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('source_unit', models.CharField(choices=[('GRAM', 'Gram'), ('KG', 'Kg'), ('ML', 'ML'), ('LITRE', 'Litre'), ('PIECE', 'Piece'), ('BAG', 'Bag'), ('BOX', 'Box'), ('BOTTLE', 'Bottle'), ('PACKET', 'Packet'), ('CARTON', 'Carton')], max_length=20)),
                ('destination_boxes', models.PositiveIntegerField(help_text='How many new sellable boxes/packs are created')),
                ('packing_material_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('packing_material_unit', models.CharField(choices=[('GRAM', 'Gram'), ('KG', 'Kg'), ('ML', 'ML'), ('LITRE', 'Litre'), ('PIECE', 'Piece'), ('BAG', 'Bag'), ('BOX', 'Box'), ('BOTTLE', 'Bottle'), ('PACKET', 'Packet'), ('CARTON', 'Carton')], default='PIECE', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('stock_applied', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_repacking_batches', to=settings.AUTH_USER_MODEL)),
                ('destination_product_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repacking_outputs', to='core.productpacksize')),
                ('packing_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repacking_packing_materials', to='core.inventoryitem')),
                ('source_inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repacking_sources', to='core.inventoryitem')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='purchasebill',
            unique_together={('party', 'bill_number')},
        ),
    ]
