# Generated by Django 5.2.4 on 2026-06-04 19:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_productstocktransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProductionFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_output_qty', models.DecimalField(decimal_places=3, default=Decimal('100.000'), max_digits=14)),
                ('base_output_unit', models.CharField(choices=[('KG', 'Kg'), ('LITRE', 'Litre')], default='KG', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_production_formulas', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_formula', to='core.product')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFormulaRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit', models.CharField(default='KG', max_length=20)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formula_raw_materials', to='core.inventoryitem')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='core.productproductionformula')),
            ],
            options={
                'ordering': ['inventory_item__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFormulaPackMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_basis', models.CharField(choices=[('PER_UNIT', 'Per Bottle / Label / Pouch'), ('PER_BOX', 'Per Outer Box / Carton')], default='PER_UNIT', max_length=20)),
                ('quantity_required', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=14)),
                ('unit', models.CharField(default='PIECE', max_length=20)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formula_pack_materials', to='core.inventoryitem')),
                ('product_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_pack_materials', to='core.productpacksize')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_materials', to='core.productproductionformula')),
            ],
            options={
                'ordering': ['product_pack__pack_size', 'inventory_item__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('output_unit', models.CharField(default='KG', max_length=20)),
                ('production_date', models.DateField(default=django.utils.timezone.localdate)),
                ('total_raw_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_packing_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_production_runs_created', to=settings.AUTH_USER_MODEL)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='smart_production_runs', to='core.productproductionformula')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='smart_production_runs', to='core.product')),
            ],
            options={
                'ordering': ['-production_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductProductionRunMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('RAW', 'Raw Material'), ('PACKING', 'Packing Material')], max_length=20)),
                ('required_qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit', models.CharField(default='KG', max_length=20)),
                ('available_before', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='smart_production_materials', to='core.inventoryitem')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.productproductionrun')),
            ],
            options={
                'ordering': ['material_type', 'inventory_item__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductProductionRunOutputPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_boxes', models.PositiveIntegerField(default=0)),
                ('units_per_box', models.PositiveIntegerField(default=1)),
                ('cost_per_box', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('product_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='smart_production_outputs', to='core.productpacksize')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_packs', to='core.productproductionrun')),
            ],
            options={
                'ordering': ['product_pack__pack_size'],
            },
        ),
    ]
