# Generated by Django 5.2.4 on 2026-06-05 07:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_productproductionformula_productformularawmaterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproductionrun',
            name='labour_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='productproductionrun',
            name='other_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
