# Generated by Django 5.2.4 on 2026-06-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_productproductionrun_labour_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='add_to_gstr2b',
            field=models.BooleanField(default=False, help_text='If enabled, this purchase bill will appear in GSTR-2B report.'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='gstr2b_added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
