# Generated by Django 5.2.4 on 2026-06-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_purchasebill_add_to_gstr2b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerinvoice',
            name='add_to_gstr1',
            field=models.BooleanField(default=False, help_text='If enabled, this sales invoice will appear in GSTR-1 report.'),
        ),
        migrations.AddField(
            model_name='dealerinvoice',
            name='gstr1_added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerinvoice',
            name='gstr1_code',
            field=models.CharField(blank=True, help_text='ARVIS = Add to GSTR-1, ARVISSMYVISION = Do not add to GSTR-1', max_length=40, null=True),
        ),
    ]
