# Generated by Django 5.2.4 on 2026-06-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_dealerinvoice_add_to_gstr1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='technical_name',
            field=models.CharField(blank=True, help_text='Technical / chemical name of the product', max_length=255, null=True),
        ),
    ]
