# Generated by Django 5.2.4 on 2026-06-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_employeetadafundreleasebatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tada_applicable',
            field=models.BooleanField(default=True, help_text='If enabled, employee can use TA/DA attendance, odometer and DA claims.'),
        ),
    ]
